// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/subscribe/subscribe.proto

package subscribe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Subscription) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{3}
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{5}
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscribe_subscribe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_proto_subscribe_subscribe_proto protoreflect.FileDescriptor

const file_proto_subscribe_subscribe_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/subscribe/subscribe.proto\x12\fsubscribe.v1\"8\n" +
	"\fSubscription\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"E\n" +
	"\x19CreateSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"E\n" +
	"\x19DeleteSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\x1a\n" +
	"\x18ListSubscriptionsRequest\"V\n" +
	"\x14SubscriptionResponse\x12>\n" +
	"\fsubscription\x18\x01 \x01(\v2\x1a.subscribe.v1.SubscriptionR\fsubscription\"\x1c\n" +
	"\x1aDeleteSubscriptionResponse\"]\n" +
	"\x19ListSubscriptionsResponse\x12@\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1a.subscribe.v1.SubscriptionR\rsubscriptions2\xbd\x02\n" +
	"\tSubscribe\x12a\n" +
	"\x12CreateSubscription\x12'.subscribe.v1.CreateSubscriptionRequest\x1a\".subscribe.v1.SubscriptionResponse\x12g\n" +
	"\x12DeleteSubscription\x12'.subscribe.v1.DeleteSubscriptionRequest\x1a(.subscribe.v1.DeleteSubscriptionResponse\x12d\n" +
	"\x11ListSubscriptions\x12&.subscribe.v1.ListSubscriptionsRequest\x1a'.subscribe.v1.ListSubscriptionsResponseB%Z#repo-stat/proto/subscribe;subscribeb\x06proto3"

var (
	file_proto_subscribe_subscribe_proto_rawDescOnce sync.Once
	file_proto_subscribe_subscribe_proto_rawDescData []byte
)

func file_proto_subscribe_subscribe_proto_rawDescGZIP() []byte {
	file_proto_subscribe_subscribe_proto_rawDescOnce.Do(func() {
		file_proto_subscribe_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscribe_subscribe_proto_rawDesc), len(file_proto_subscribe_subscribe_proto_rawDesc)))
	})
	return file_proto_subscribe_subscribe_proto_rawDescData
}

var file_proto_subscribe_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_subscribe_subscribe_proto_goTypes = []any{
	(*Subscription)(nil),               // 0: subscribe.v1.Subscription
	(*CreateSubscriptionRequest)(nil),  // 1: subscribe.v1.CreateSubscriptionRequest
	(*DeleteSubscriptionRequest)(nil),  // 2: subscribe.v1.DeleteSubscriptionRequest
	(*ListSubscriptionsRequest)(nil),   // 3: subscribe.v1.ListSubscriptionsRequest
	(*SubscriptionResponse)(nil),       // 4: subscribe.v1.SubscriptionResponse
	(*DeleteSubscriptionResponse)(nil), // 5: subscribe.v1.DeleteSubscriptionResponse
	(*ListSubscriptionsResponse)(nil),  // 6: subscribe.v1.ListSubscriptionsResponse
}
var file_proto_subscribe_subscribe_proto_depIdxs = []int32{
	0, // 0: subscribe.v1.SubscriptionResponse.subscription:type_name -> subscribe.v1.Subscription
	0, // 1: subscribe.v1.ListSubscriptionsResponse.subscriptions:type_name -> subscribe.v1.Subscription
	1, // 2: subscribe.v1.Subscribe.CreateSubscription:input_type -> subscribe.v1.CreateSubscriptionRequest
	2, // 3: subscribe.v1.Subscribe.DeleteSubscription:input_type -> subscribe.v1.DeleteSubscriptionRequest
	3, // 4: subscribe.v1.Subscribe.ListSubscriptions:input_type -> subscribe.v1.ListSubscriptionsRequest
	4, // 5: subscribe.v1.Subscribe.CreateSubscription:output_type -> subscribe.v1.SubscriptionResponse
	5, // 6: subscribe.v1.Subscribe.DeleteSubscription:output_type -> subscribe.v1.DeleteSubscriptionResponse
	6, // 7: subscribe.v1.Subscribe.ListSubscriptions:output_type -> subscribe.v1.ListSubscriptionsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_subscribe_subscribe_proto_init() }
func file_proto_subscribe_subscribe_proto_init() {
	if File_proto_subscribe_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscribe_subscribe_proto_rawDesc), len(file_proto_subscribe_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscribe_subscribe_proto_goTypes,
		DependencyIndexes: file_proto_subscribe_subscribe_proto_depIdxs,
		MessageInfos:      file_proto_subscribe_subscribe_proto_msgTypes,
	}.Build()
	File_proto_subscribe_subscribe_proto = out.File
	file_proto_subscribe_subscribe_proto_goTypes = nil
	file_proto_subscribe_subscribe_proto_depIdxs = nil
}
