// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
RETURNING id, owner, repo, created_at
`

type CreateSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.Repo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, owner, repo, created_at
FROM subscriptions
ORDER BY owner, repo
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
