// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/collector/collector.proto

package collector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepositoryInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryInfoRequest) Reset() {
	*x = GetRepositoryInfoRequest{}
	mi := &file_proto_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryInfoRequest) ProtoMessage() {}

func (x *GetRepositoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepositoryInfoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepositoryInfoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetRepositoryInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int64                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int64                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryInfoResponse) Reset() {
	*x = GetRepositoryInfoResponse{}
	mi := &file_proto_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryInfoResponse) ProtoMessage() {}

func (x *GetRepositoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryInfoResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetRepositoryInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRepositoryInfoResponse) GetStars() int64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *GetRepositoryInfoResponse) GetForks() int64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *GetRepositoryInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetSubscriptionsInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsInfoRequest) Reset() {
	*x = GetSubscriptionsInfoRequest{}
	mi := &file_proto_collector_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsInfoRequest) ProtoMessage() {}

func (x *GetSubscriptionsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{2}
}

type GetSubscriptionsInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*RepositoryInfo      `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsInfoResponse) Reset() {
	*x = GetSubscriptionsInfoResponse{}
	mi := &file_proto_collector_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsInfoResponse) ProtoMessage() {}

func (x *GetSubscriptionsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsInfoResponse) GetRepositories() []*RepositoryInfo {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type RepositoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int64                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int64                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	mi := &file_proto_collector_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{4}
}

func (x *RepositoryInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RepositoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RepositoryInfo) GetStars() int64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *RepositoryInfo) GetForks() int64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *RepositoryInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_collector_collector_proto protoreflect.FileDescriptor

const file_proto_collector_collector_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/collector/collector.proto\x12\fcollector.v1\"D\n" +
	"\x18GetRepositoryInfoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\xa5\x01\n" +
	"\x19GetRepositoryInfoResponse\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x03R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x03R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x1d\n" +
	"\x1bGetSubscriptionsInfoRequest\"`\n" +
	"\x1cGetSubscriptionsInfoResponse\x12@\n" +
	"\frepositories\x18\x01 \x03(\v2\x1c.collector.v1.RepositoryInfoR\frepositories\"\x9a\x01\n" +
	"\x0eRepositoryInfo\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x03R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x03R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\xe0\x01\n" +
	"\tCollector\x12d\n" +
	"\x11GetRepositoryInfo\x12&.collector.v1.GetRepositoryInfoRequest\x1a'.collector.v1.GetRepositoryInfoResponse\x12m\n" +
	"\x14GetSubscriptionsInfo\x12).collector.v1.GetSubscriptionsInfoRequest\x1a*.collector.v1.GetSubscriptionsInfoResponseB%Z#repo-stat/proto/collector;collectorb\x06proto3"

var (
	file_proto_collector_collector_proto_rawDescOnce sync.Once
	file_proto_collector_collector_proto_rawDescData []byte
)

func file_proto_collector_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collector_collector_proto_rawDesc), len(file_proto_collector_collector_proto_rawDesc)))
	})
	return file_proto_collector_collector_proto_rawDescData
}

var file_proto_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_collector_collector_proto_goTypes = []any{
	(*GetRepositoryInfoRequest)(nil),     // 0: collector.v1.GetRepositoryInfoRequest
	(*GetRepositoryInfoResponse)(nil),    // 1: collector.v1.GetRepositoryInfoResponse
	(*GetSubscriptionsInfoRequest)(nil),  // 2: collector.v1.GetSubscriptionsInfoRequest
	(*GetSubscriptionsInfoResponse)(nil), // 3: collector.v1.GetSubscriptionsInfoResponse
	(*RepositoryInfo)(nil),               // 4: collector.v1.RepositoryInfo
}
var file_proto_collector_collector_proto_depIdxs = []int32{
	4, // 0: collector.v1.GetSubscriptionsInfoResponse.repositories:type_name -> collector.v1.RepositoryInfo
	0, // 1: collector.v1.Collector.GetRepositoryInfo:input_type -> collector.v1.GetRepositoryInfoRequest
	2, // 2: collector.v1.Collector.GetSubscriptionsInfo:input_type -> collector.v1.GetSubscriptionsInfoRequest
	1, // 3: collector.v1.Collector.GetRepositoryInfo:output_type -> collector.v1.GetRepositoryInfoResponse
	3, // 4: collector.v1.Collector.GetSubscriptionsInfo:output_type -> collector.v1.GetSubscriptionsInfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_collector_collector_proto_init() }
func file_proto_collector_collector_proto_init() {
	if File_proto_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collector_collector_proto_rawDesc), len(file_proto_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_collector_proto = out.File
	file_proto_collector_collector_proto_goTypes = nil
	file_proto_collector_collector_proto_depIdxs = nil
}
