FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /collector ./cmd/collector

FROM gcr.io/distroless/static-debian12

COPY --from=builder /collector /collector

EXPOSE 2001

ENTRYPOINT ["/collector"]
