// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	Owner       string
	Repo        string
	FullName    string
	Description string
	Stars       int64
	Forks       int64
	CreatedAt   string
	Status      string
	Error       string
	UpdatedAt   pgtype.Timestamptz
}
