// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"
)

const getRepository = `-- name: GetRepository :one
SELECT owner, repo, full_name, description, stars, forks, created_at, status, error, updated_at
FROM repositories
WHERE owner = $1 AND repo = $2
`

type GetRepositoryParams struct {
	Owner string
	Repo  string
}

func (q *Queries) GetRepository(ctx context.Context, arg GetRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, arg.Owner, arg.Repo)
	var i Repository
	err := row.Scan(
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.Status,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryError = `-- name: UpsertRepositoryError :exec
INSERT INTO repositories (owner, repo, status, error, updated_at)
VALUES ($1, $2, 'error', $3, now())
ON CONFLICT (owner, repo) DO UPDATE
SET status = 'error',
    error = EXCLUDED.error,
    updated_at = now()
`

type UpsertRepositoryErrorParams struct {
	Owner string
	Repo  string
	Error string
}

func (q *Queries) UpsertRepositoryError(ctx context.Context, arg UpsertRepositoryErrorParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryError, arg.Owner, arg.Repo, arg.Error)
	return err
}

const upsertRepositoryInfo = `-- name: UpsertRepositoryInfo :exec
INSERT INTO repositories (owner, repo, full_name, description, stars, forks, created_at, status, error, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'ready', '', now())
ON CONFLICT (owner, repo) DO UPDATE
SET full_name = EXCLUDED.full_name,
    description = EXCLUDED.description,
    stars = EXCLUDED.stars,
    forks = EXCLUDED.forks,
    created_at = EXCLUDED.created_at,
    status = 'ready',
    error = '',
    updated_at = now()
`

type UpsertRepositoryInfoParams struct {
	Owner       string
	Repo        string
	FullName    string
	Description string
	Stars       int64
	Forks       int64
	CreatedAt   string
}

func (q *Queries) UpsertRepositoryInfo(ctx context.Context, arg UpsertRepositoryInfoParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryInfo,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.CreatedAt,
	)
	return err
}

const upsertRepositoryPending = `-- name: UpsertRepositoryPending :exec
INSERT INTO repositories (owner, repo, status, error, updated_at)
VALUES ($1, $2, 'pending', '', now())
ON CONFLICT (owner, repo) DO UPDATE
SET status = 'pending',
    error = '',
    updated_at = now()
`

type UpsertRepositoryPendingParams struct {
	Owner string
	Repo  string
}

func (q *Queries) UpsertRepositoryPending(ctx context.Context, arg UpsertRepositoryPendingParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryPending, arg.Owner, arg.Repo)
	return err
}
